version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:17.2.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Install ava
          command: |
            npm install --save-dev ava
            npm install --save-dev c8
            npm install --save-dev nyc

      - run:
          name: Run tests
          command: |
            npm run test
            npm run report
      - store_artifacts:
          path: coverage
