version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Install ava
          command: |
            npm install ava
            npm install c8
            npm install nyc
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Run report
          command: npm report

      - store_artifacts:
          path: coverage
