version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Install ava
          command: |
            npm install ava --save-dev
            npm install c8 --save-dev
            npm install nyc --save-dev
      - run:
          name: Run tests
          command: |
            npm run test
            npm run report
      - store_artifacts:
          path: coverage
